/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#434655",
        "tertiary-fixed": "#e4e2e1",
        "tertiary-container": "#6e6d6d",
        "on-primary-fixed-variant": "#003ea8",
        "surface-dim": "#11131b",
        "surface-container-high": "#282a32",
        "primary": "#b4c5ff",
        "on-primary-container": "#eeefff",
        "on-primary-fixed": "#00174b",
        "on-secondary-fixed-variant": "#474646",
        "surface-container": "#1d1f27",
        "secondary-fixed": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "on-secondary": "#313030",
        "on-tertiary-fixed-variant": "#474746",
        "error": "#ffb4ab",
        "secondary": "#c8c6c5",
        "inverse-surface": "#e1e2ed",
        "surface-tint": "#b4c5ff",
        "primary-container": "#2563eb",
        "on-background": "#e1e2ed",
        "on-secondary-container": "#bab8b7",
        "on-secondary-fixed": "#1c1b1b",
        "on-error": "#690005",
        "secondary-container": "#4a4949",
        "on-tertiary-fixed": "#1b1c1c",
        "surface-container-low": "#191b23",
        "on-tertiary-container": "#f3f0ef",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary": "#c8c6c5",
        "primary-fixed-dim": "#b4c5ff",
        "on-surface": "#e1e2ed",
        "inverse-on-surface": "#2e3039",
        "error-container": "#93000a",
        "surface-bright": "#373942",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-primary": "#002a78",
        "surface": "#11131b",
        "on-tertiary": "#303030",
        "surface-container-lowest": "#0c0e16",
        "surface-variant": "#32343d",
        "primary-fixed": "#dbe1ff",
        "surface-container-highest": "#32343d",
        "on-surface-variant": "#c3c6d7",
        "outline": "#8d90a0",
        "inverse-primary": "#0053db",
        "background": "#11131b",
        "deep-base": "#0A0A0A",
        "surface-elevated": "#131313",
        "surface-overlay": "#1E1E1E",
        "border-subtle": "#2A2A2A"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "title-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-md": ["Inter"],
        "display-sm": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "body-sm": ["12px", {"lineHeight": "18px", "fontWeight": "400"}],
        "title-md": ["16px", {"lineHeight": "24px", "fontWeight": "500"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "500"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "display-sm": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "code-md": ["13px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
